{{- if .Values.connectInject.proxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-dns-resolv-conf
  namespace: {{ .Release.Namespace }}
data:
  resolv.conf: |  
    nameserver {{ .Values.connectInject.proxy.dns.nameserver | default "172.20.0.10" }}
    search svc.cluster.local cluster.local
    options ndots:5

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events {
      worker_connections  10240;
    }
    
    stream {
      upstream myupstream {
        server {{ template "consul.fullname" . }}-connect-injector.{{ .Release.Namespace }}.svc.cluster.local:443;
      }
      
      server {
        listen       {{ .Values.connectInject.proxy.httpsPort | default 9443 }};
        proxy_pass myupstream;

        ssl_protocols               TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers                 EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
        ssl_prefer_server_ciphers   on;
      }
    }
---