{{- if .Values.connectInject.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: proxy-connect-injector
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: proxy-connect-injector
  ports:
    - port: 443
      targetPort: webhook
{{- end }}